DWS/Django/supertodo/tasks/urls.py
from django.urls import path

from . import views

app_name = 'tasks'


urlpatterns = [
    path('', views.task_list, name='task-list'),
    path('task/<slug:task_slug>/', views.task_detail, name='task-detail'),
    path('done/', views.task_done, name='task-done'),
    path('pending/', views.task_pendig, name='task-pendig'),
    path('add/', views.add_task, name='add-task'),
    path('task/<slug:task_slug>/toggle/', views.task_toggle, name='task-toggle'),
    path('task/<slug:task_slug>/edit/', views.task_edit, name='task-edit'),
    path('task/<slug:task_slug>/delete/', views.task_delete, name='task-delete'),
]

DWS/Django/supertodo/tasks/models.py
from django.db import models

# Create your models here.


class Task(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(max_length=120, unique=True)
    description = models.TextField(max_length=300)
    done = models.BooleanField()
    complete_before = models.DateTimeField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    # black=True
    def __str__(self):
        return self.name

DWS/Django/supertodo/tasks/forms.py
from django import forms

from .models import Task


class AddTaskForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'

    class Meta:
        model = Task
        fields = ('name', 'description', 'complete_before')
        # widgets = {'title': forms.widgets.TextInput(attrs={'class': 'form-control'})}

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'

DWS/Django/supertodo/tasks/views.py
from django.shortcuts import redirect, render
from django.utils.text import slugify

# Create your views here.
from tasks.models import Task

from .forms import AddTaskForm




def task_list(request):
    # tasks = Task.objects.all()
    completed_tasks = Task.objects.filter(done=True)
    pending_tasks = Task.objects.filter(done=False)
    # print(len(tasks))
    for j in completed_tasks:
        print(j.slug)
    return render(
        request,
        'tasks/task_list.html',
        {
            'completed_tasks': completed_tasks,
            'pending_tasks': pending_tasks,
        },
    )


def task_detail(request, task_slug: str):
    # task = Task.objects.all()
    task = Task.objects.get(slug=task_slug)
    return render(request, 'tasks/task_detail.html', dict(task=task))


def task_done(request):
    tasks = Task.objects.filter(done=True)
    return render(
        request,
        'tasks/task_done.html',
        {'tasks': tasks},
    )


def task_pendig(request):
    tasks = Task.objects.filter(done=False)

    return render(
        request,
        'tasks/tasks_pending.html',
        {'tasks': tasks},
    )


def add_task(request):
    pass
    if request.method == 'GET':
        task = AddTaskForm()
    else:
        if (task := AddTaskForm(data=request.POST)).is_valid():
            task = task.save(commit=False)
            task.slug = slugify(task.name)
            task.done = False
            task.save()
            return redirect('tasks:task-list')
    return render(request, 'tasks/add_task.html', dict(form=task))


def task_toggle(request,task_slug: str):
    task = Task.objects.get(slug=task_slug)
    if task.done:
        task.done= False
    else:
        task.done = True
    task.save()
    return render(request, 'tasks/task_toggle.html', dict(task=task))


def task_edit(request,task_slug: str):
    task = Task.objects.get(slug=task_slug)

    if request.method == 'POST':
        form = AddTaskForm(request.POST, instance=task)
        if form.is_valid():
            form.save()
            return redirect('tasks:task-list')
    else:
        
        form = AddTaskForm(instance=task)
    
    return render(request, 'tasks/task_edit.html', {'form': form, 'task': task})

    


def task_delete(request,task_slug: str):
    task = Task.objects.get(slug=task_slug)
    if request.method == "POST":
        task.delete()
        return redirect('tasks:task-list')

    return render(request, 'tasks/task_delete.html', {'task': task})

DWS/Django/supertodo/tasks/templates/tasks/add_task.html
{% extends "tasks/base.html" %}
{% block title %}Crear una tarea{% endblock title %}

{% block body %}
  <h1>Crear nuevo post</h1>
  <form method="post" novalidate>
    {% csrf_token %}
    {{ form }}
  <button type="submit">
    <p>Crear Tarea</p>
  </button>
  </form>
  <a href="{% url 'tasks:task-list'%}"><button>Cancelar</button></a>


{% endblock body %}

DWS/Django/supertodo/tasks/templates/tasks/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="x-ua-compatible" content="ie=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <title>{% block title %}Tareas{% endblock %}</title>

    {% comment %} <link rel="stylesheet" href="{% static 'blog/custom.css' %}"> {% endcomment %}
    <!-- <link rel="icon" href="images/favicon.png" /> -->
  </head>

  <body>
     {% block body %}{% endblock body %}
    <!-- <script src="js/scripts.js"></script> -->
  </body>
</html>

DWS/Django/supertodo/tasks/templates/tasks/task_delete.html
{% extends "tasks/base.html" %}

{% block title %}Eliminar Tarea{% endblock title %}

{% block body %}
  <h1>Eliminar Tarea</h1>
  <p>¿Estás seguro de que deseas eliminar la tarea "{{ task.name }}"?</p>
  
  <form method="POST">
    {% csrf_token %}
    <button type="submit">Eliminar</button>
    <a href="{% url 'tasks:task-list' %}"><button type="button">Cancelar</button></a>
  </form>
{% endblock body %}

DWS/Django/supertodo/tasks/templates/tasks/task_detail.html
{% extends "tasks/base.html" %}
{% block title %}Detalle de la Tarea{% endblock title %}

{% block body %}

<h1>Detalles de la Tarea</h1>

  <p><strong>Nombre:</strong> {{ task.name }}</p>
  <p><strong>Slug:</strong> {{ task.slug }}</p>
  <p><strong>Descripción:</strong> {{ task.description }}</p>
  <p><strong>Completada:</strong> {{ task.done|yesno:"Sí,No" }}</p>
  <p><strong>Fecha límite:</strong> {{ task.complete_before|date:"d M Y H:i" }}</p>
  <p><strong>Creada en:</strong> {{ task.created_at|date:"d M Y H:i" }}</p>
  <p><strong>Última actualización:</strong> {{ task.updated_at|date:"d M Y H:i" }}</p>

<!-- <h1>{{ task.title }}</h1>
<span class="badge text-bg-secondary mb-3">
  <i class="bi bi-pen"></i>
  {{ task.created_at }}
</span>
<p>{{ post.content }}</p> -->

<a href="{% url 'tasks:task-list'%}"><button>Volver</button></a>
  
  
{% endblock body %}

DWS/Django/supertodo/tasks/templates/tasks/task_done.html
{% extends "tasks/base.html" %}
{% block title %}Tareas Pendientes{% endblock title %}

{% block body %}
{% for task in tasks %}
<div>
  <h1>{{task.name}}</h1>
  <p>{{task.description}}</p>
  <p>Tiempo para poder hacerlo: {{task.done}}</p>
  <p>Fecha de creacion: {{task.complete_before}}</p>
  <p>Ultima actualizacion: {{task.updated_at}}</p>
</div>
{% endfor %}
<a href="{% url 'tasks:task-list'%}"><button>Volver</button></a>
  
  
{% endblock body %}

DWS/Django/supertodo/tasks/templates/tasks/task_edit.html
{% extends "tasks/base.html" %}
{% block title %}Detalle de la Tarea{% endblock title %}

{% block body %}

<h1>Crear nuevo post</h1>
  <form method="post" novalidate>
    {% csrf_token %}
    {{ form }}
  <button type="submit">
    <p>Guardar</p>
  </button>
  </form>
  <a href="{% url 'tasks:task-list'%}"><button>Cancelar</button></a>
  
  
{% endblock body %}

DWS/Django/supertodo/tasks/templates/tasks/task_list.html
{% extends "tasks/base.html" %}
{% block title %}Tareas | Home{% endblock title %}

{% block body %}
  <h1>Tareas</h1>
    <div>
      <a href="{% url 'tasks:task-done'%}"><button>Done</button></a>
      <a href="{% url 'tasks:task-pendig'%}"><button>Pending</button></a>
      <a href="{% url 'tasks:add-task'%}"><button>ADD</button></a>
    </div>
    
      {% for task in pending_tasks %}
      <div>
        <a href="{% url 'tasks:task-detail' task.slug %}">{{task.name}}</a>
        {% comment %} <p>{{task.description}}</p> {% endcomment %}
        {% comment %} <p>Tiempo para poder hacerlo: {{task.complete_before}}</p>
        <p>Fecha de creacion: {{task.created_at}}</p>
        <p>Ultima actualizacion: {{task.updated_at}}</p> {% endcomment %}
        <a href="{% url 'tasks:task-toggle' task.slug %}"><button>Cambiar</button></a>
        <a href="{% url 'tasks:task-edit' task.slug %}"><button>Editar</button></a>
        <a href="{% url 'tasks:task-delete' task.slug %}"><button>Eliminar</button></a>
      </div>
      {% endfor %}
      {% for task in completed_tasks %}
        <div>
          <a href="{% url 'tasks:task-detail' task.slug %}">{{task.name}}</a>
          {% comment %} <p>{{task.description}}</p> {% endcomment %}
          {% comment %} <p>Tiempo para poder hacerlo: {{task.complete_before}}</p>
          <p>Fecha de creacion: {{task.created_at}}</p>
          <p>Ultima actualizacion: {{task.updated_at}}</p> {% endcomment %}
          <a href="{% url 'tasks:task-toggle' task.slug %}"><button>Cambiar</button></a>
          <a href="{% url 'tasks:task-edit' task.slug %}"><button>Editar</button></a>
          <button>Eliminar</button> 
        </div>
      {% endfor %}
  
 
{% endblock body %}

DWS/Django/supertodo/tasks/templates/tasks/task_toggle.html
{% extends "tasks/base.html" %}
{% block title %}Detalle de la Tarea{% endblock title %}

{% block body %}

<h1>Detalles de la Tarea</h1>
<!-- 
  <p><strong>Nombre:</strong> {{ task.name }}</p>
  <p><strong>Slug:</strong> {{ task.slug }}</p>
  <p><strong>Descripción:</strong> {{ task.description }}</p>
  <p><strong>Completada:</strong> {{ task.done|yesno:"Sí,No" }}</p>
  <p><strong>Fecha límite:</strong> {{ task.complete_before|date:"d M Y H:i" }}</p>
  <p><strong>Creada en:</strong> {{ task.created_at|date:"d M Y H:i" }}</p>
  <p><strong>Última actualización:</strong> {{ task.updated_at|date:"d M Y H:i" }}</p>

<!-- <h1>{{ task.title }}</h1>
<span class="badge text-bg-secondary mb-3">
  <i class="bi bi-pen"></i>
  {{ task.created_at }}
</span>
<p>{{ post.content }}</p> -->

<a href="{% url 'tasks:task-list'%}"><button>Volver</button></a>
   -->
  
{% endblock body %}

DWS/Django/supertodo/tasks/templates/tasks/tasks_pending.html
{% extends "tasks/base.html" %}
{% block title %}Tareas Pendientes{% endblock title %}

{% block body %}
{% for task in tasks %}
<div>
  <h1>{{task.name}}</h1>
  <p>{{task.description}}</p>
  {% comment %} <p>Tiempo para poder hacerlo: {{task.complete_before}}</p>
  <p>Fecha de creacion: {{task.created_at}}</p>
  <p>Ultima actualizacion: {{task.updated_at}}</p> {% endcomment %}
  <button>Cambiar</button>
  <button>Editar</button>
  <button>Eliminar</button>
</div>
{% endfor %}
  
  <a href="{% url 'tasks:task-list'%}"><button>Volver</button></a>
{% endblock body %}