DWS/supertodo/tasks/urls.py
# from django.contrib import admin
from django.urls import path

from . import views

app_name = 'tasks'

urlpatterns = [
    path('', views.home, name='home'),
    path('task/<task_slug>/', views.task_detail, name='task_detail'),
    path('add_task/', views.add_task, name='add_task'),
]

DWS/supertodo/tasks/models.py
from django.db import models

# Create your models here.


class Task(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField(max_length=120, unique=True)
    description = models.TextField(max_length=300)
    done = models.BooleanField()
    time_finish = models.DateField()

    def __str__(self):
        return self.title

DWS/supertodo/tasks/forms.py
from django import forms

from .models import Task

# class AddTaskForm(forms.Form):
#     title = forms.CharField(max_length=100)
#     description = forms.CharField(widget=forms.widgets.Textarea)
#     time_finish = forms.DateField()


class AddTaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ('title',)

DWS/supertodo/tasks/views.py
# Create your views here.
from django.shortcuts import redirect, render
from django.utils.text import slugify

from tasks.models import Task

from .forms import AddTaskForm


def home(request):
    num_tasks = Task.objects.count()
    tasks = Task.objects.all()
    print('Hola estoy en el home')
    return render(
        request,
        'tasks/home.html',
        {'num_tasks': num_tasks, 'tasks': tasks},
    )


def task_detail(request, task_slug):
    # print(f'Tiene sentido que {post_id}')
    task = Task.objects.get(slug=task_slug)
    # print(f'Tiene sentido que {post}')
    return render(request, 'tasks/task_detail.html', dict(task=task))


def add_task(request):
    if request.method == 'POST':
        if (task := AddTaskForm(request.POST)).is_valid():
            task = task.save(commit=False)
            task.slug = slugify(task.title)
            task.save()
            return redirect('tasks:home')

    else:
        print('Funciona')
        # print(reques)
        task = AddTaskForm()

    return render(request, 'tasks/add_task.html', dict(form=task))


# def index(request):
#     return HttpResponse("Hello, world. You're at the polls index.")

DWS/supertodo/tasks/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="x-ua-compatible" content="ie=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <title>{% block title %}Tasks{% endblock %}</title>

    <link rel="stylesheet" href="{% static 'blog/custom.css' %}">
    <!-- <link rel="icon" href="images/favicon.png" /> -->
  </head>

  <body>
     {% block body %}{% endblock body %}
    <!-- <script src="js/scripts.js"></script> -->
  </body>
</html>

DWS/supertodo/tasks/templates/tasks/add_task.html
{% extends "./base.html"%}
{% block title %}Tareas | Home{% endblock title %}


{% block body %}
{% comment %} <h1>Funciona:</h1> {% endcomment %}
  <form method="post" novalidate>
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Enviar">
  </form>


{% endblock body %}

DWS/supertodo/tasks/templates/tasks/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    {% comment %} <meta http-equiv="x-ua-compatible" content="ie=edge" /> {% endcomment %}
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <title>{% block title %}Tasks{% endblock %}</title>

    <link rel="stylesheet" href="{% static 'tasks/custom.css' %}">
    <!-- <link rel="icon" href="images/favicon.png" /> -->
  </head>

  <body>
     {% block body %}{% endblock body %}
    <!-- <script src="js/scripts.js"></script> -->
  </body>
</html>

DWS/supertodo/tasks/templates/tasks/home.html
{% extends "./base.html"%}
{% block title %}Tareas | Home{% endblock title %}

{% block body %}

  <div class="titulo">
    <h1>Tareas</h1>
    <p>we already have more than {{num_tasks}} task{{num_tasks|pluralize}}</p>

  </div>
  
  {% comment %} <p>contiue......</p>
  <p>Mi primera plantilla</p> {% endcomment %}

 
 
  {% for task in tasks%}
    <div class="tarea" >
      <h2>Titulo: {{task.title}}</h2>
        <p>
          Description: {{task.description}}
        </p>
        {% if task.done%}
            <p>Tarea realizada</p>
        {% else %}
          <p>Tarea no realizada</p>
        {% endif %}
        <p>
          Creado: {{task.time_finish}}
        </p>
        <p>Mas detalles...<a href="{% url 'tasks:task_detail' task.slug %}">Tasks more....</a></p>
        {% comment %} {{task.content|truncatewords:20}}  {% endcomment %}
      

    </div>
    
  {% endfor %}
  {% endblock body %}

DWS/supertodo/tasks/templates/tasks/task_detail.html
{% extends "./base.html"%}

{% block title %}Tarea | {{ task.title }}{% endblock title %}

{% block body %}
  <div class="detalle_task">
    {% comment %} <h1>Titulo</h1> {% endcomment %}
      <h1>{{ task.title }}</h1>
      <div class="task-date">Creado la tarea: {{task.time_finish }}</div>
      <p>Description: {{ task.description }}</p>
      <a href="{% url 'tasks:home' %}">Back to 🏠</a>
    
    

  </div>
  
{% endblock body %}